name: Create Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Create new release"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Update app version
        run: |
          npm version ${{ inputs.release }}
          git push --follow-tags

      - name: Merge develop in main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
